### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by IllDepence** [rroessler1/ebmodule#1]
Hi,

I saw that you [recently commented](https://github.com/aehlke/ebmodule/pull/1#issuecomment-736941369) on the pull request you created for ebmodule and suggested moving conversation here.

Similar to CalculusAce, I'm struggling with the setup and would be super happy about some pointers. Could be some trivial mistake.

Here's what I did:

0. (In a previous attempt something was complaining about not finding eb.h, so I installed eb [from this repo](https://github.com/aehlke/eb.git))
1. cloned your repo
2. checked out the python3 branch
3. ran `python3 setup.py build` (also tried python2), which failed

Here's the output I got: [stdout](https://pastebin.com/raw/gYwvqLy0), [stderr](https://pastebin.com/raw/C9hMtvAN).
For context: I'm running Ubuntu 18.04

Thanks in advance for any help. ( • ᴗ • )

**Comment by rroessler1** [comment]
Looking at stderr I'm wondering if you have a different version of libeb installed?  This is what I used (also Ubuntu):

```
# EPWING reader
# Required C library dependency
mkdir epwing-reader
cd epwing-reader/
curl -L -o eblib.tar.gz "https://github.com/mistydemeo/eb/releases/download/v4.4.3/eb-4.4.3.tar.bz2"
tar xvf eblib.tar.gz
rm eblib.tar.gz
cd eb-4.4.3/
./configure
make
make check
sudo make install
cd ..
```

Seems to work on my machine, just tested, unless there's another library I'm missing.  Can you try that and let me know?

**Comment by IllDepence** [comment]
Apparently I forgot about this 3.5 years ago.

On my current machine (Debian 12) I followed your instructions and it worked. 👍

Thanks! ^_^
